// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_PIV.Context;

#nullable disable

namespace Projekt_PIV.Migrations
{
    [DbContext(typeof(EwidencjaContext))]
    partial class EwidencjaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Projekt_PIV.Models.DaneAdresowe", b =>
                {
                    b.Property<int>("Id_Adresu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Adresu"), 1L, 1);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod_pocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Adresu");

                    b.ToTable("DaneAdresowe");
                });

            modelBuilder.Entity("Projekt_PIV.Models.Faktury", b =>
                {
                    b.Property<int>("Id_Faktury")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Faktury"), 1L, 1);

                    b.Property<double>("Całkowita_kwota_do_zapłaty")
                        .HasColumnType("float");

                    b.Property<int>("Id_Klienta")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pracownika")
                        .HasColumnType("int");

                    b.Property<int>("Id_Zamówienia")
                        .HasColumnType("int");

                    b.Property<DateTime>("Termin_płatności")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Termin_wpłaty")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Faktury");

                    b.ToTable("Faktury");
                });

            modelBuilder.Entity("Projekt_PIV.Models.Klienci", b =>
                {
                    b.Property<int>("Id_Klienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Klienta"), 1L, 1);

                    b.Property<string>("Email_klienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Adresu")
                        .HasColumnType("int");

                    b.Property<string>("Imię_klienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko_klienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numer_telefonu_klienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL_klienta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Klienta");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Projekt_PIV.Models.Pracownicy", b =>
                {
                    b.Property<int>("Id_Pracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pracownika"), 1L, 1);

                    b.Property<DateTime>("Data_urodzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_zatrudnienia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_pracownika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Adresu")
                        .HasColumnType("int");

                    b.Property<string>("Imię_pracownika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko_pracownika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numer_telefonu_pracownika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL_pracownika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Pracownika");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("Projekt_PIV.Models.Produkty", b =>
                {
                    b.Property<int>("Id_Produktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produktu"), 1L, 1);

                    b.Property<double>("Cena_jednostkowa")
                        .HasColumnType("float");

                    b.Property<int>("Dostępna_ilość")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa_produktu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Produktu");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("Projekt_PIV.Models.Zamówienia", b =>
                {
                    b.Property<int>("Id_Zamówienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Zamówienia"), 1L, 1);

                    b.Property<double>("Cena_jednostkowa")
                        .HasColumnType("float");

                    b.Property<int>("Id_Produktu")
                        .HasColumnType("int");

                    b.Property<int>("Ilość")
                        .HasColumnType("int");

                    b.HasKey("Id_Zamówienia");

                    b.ToTable("Zamówienia");
                });
#pragma warning restore 612, 618
        }
    }
}
